steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/pokemon-sbx/pokemon-repo/pokemon-server', '-f', 'apps/server/Dockerfile', '.']
timeout: '1200s'
images: ['us-central1-docker.pkg.dev/pokemon-sbx/pokemon-repo/pokemon-server']
