version: '3.8'

services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://database:27017/pokemon-mx-01
    depends_on:
      - database

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
